#include<iostream>
#include<conio.h>
using namespace std;
int main()
{
	int t,n;
	t=0;
	char choice[100],ch1;
	cout<<"\n\n\t\t         ________________________";
	cout<<"\n\n\t\t         *       Quiz Game      *";
	cout<<"\n\n\t\t         ________________________";
	cout<<"\n\n\t\t==================================================";
	cout<<"\n\n\t\t-   Created By  :   Krishna Mohan Mishra  -- A17  ";
	cout<<"\n\n\t\t==================================================";
	cout<<"\n\n";
	cout<<"\n Please Enter Your Name : ";
	cin>>choice;
	cout<<"\n\n";
	cout<<"\n\n\t\t Welcome "<<choice<<"\n";
	cout<<"\n\n\t\t Loading Please wait........";
	cout<<"\n\n\t\t 1) Start Quiz";
	cout<<"\n\n\t\t 2) View Score";
	cout<<"\n\n\t\t 3) Exit Quiz";
	cout<<"\n\n Enter Your Choice :--> ";
	cin>>n;
	switch(n)
	{
		case 1:
		cout<<"\n\n\n Note :Enter answer in the a,b,c and d only...";
		cout<<"\n\n\n";
		cout<<"1) When a gas is turned into a liquid, the process is called";
		cout<<"\n\n A.Condensation \n\n B.Evaporation \n\n C.Deposition \n\n D.Sublimation";
	cout<<"\n\n Enter Your Select answer : ";
	cin>>ch1;
	if(ch1=='a')
	{
		t=t+1;
		cout<<"\n\n Correct answer....";

	}
	else
		cout<<"\n\n Sorry Wrong answer....";
		getch();
		cout<<"\n\n\n";
		cout<<"2) Which of the following parts of the sun is easily visible only during a total solar eclipse? ";
		cout<<"\n\n A.Core \n\n B.Photosphere \n\n C.Sunspots \n\n D.Corona";
		cout<<"\n\n Enter Your Select answer : ";
		cin>>ch1;
	if(ch1=='d')
	{
		t=t+1;
		cout<<"\n\n Correct answer....";

	}	else
		cout<<"\n\n Sorry Wrong answer....";
		getch();
		cout<<"\n\n\n";
		cout<<"3) Which of the following is most likely to cause a rise in the average temperature of earth's atmosphere in future?";
		cout<<"\n\n A.Atomic warfare \n\n B.CO2 from fossil fuels \n\n C.Dust clouds from volcanoes \n\n D.Depletion of earth's ozone layer";
		cout<<"\n\n Enter Your Select answer : ";
		cin>>ch1;
	if(ch1=='b')
	{
		t=t+1;
		cout<<"\n\n Correct answer....";

	}	else
		cout<<"\n\n Sorry Wrong answer....";
		getch();
		cout<<"\n\n\n";
		cout<<"4) Which of the following elements is a metal";
		cout<<"\n\n A.S \n\n B.Se \n\n C.I \n\n D.Ga";
		cout<<"\n\n Enter Your Select answer : ";
		cin>>ch1;
	if(ch1=='d')
	{
		t=t+1;
		cout<<"\n\n Correct answer....";

	}	else
		cout<<"\n\n Sorry Wrong answer....";
		getch();
		cout<<"\n\n\n";
		cout<<"5) The fastest-running terrestrial animal is";
		cout<<"\n\n A.Cheetah \n\n B.Lion \n\n C.Jaguar \n\n D.Man";
		cout<<"\n\n Enter Your Select answer : ";
		cin>>ch1;
	if(ch1=='a')
	{
		t=t+1;
		cout<<"\n\n Correct answer....";

	}	else
		cout<<"\n\n Sorry Wrong answer....";
		getch();
		cout<<"\n\n\n";
		cout<<"6) The study of phenomena at very low temperatures is called";
		cout<<"\n\n A.Heat Transfer \n\n B.Morphology \n\n C.Crystallography \n\n D.Cryogenics";
		cout<<"\n\n Enter Your Select answer : ";
		cin>>ch1;
	if(ch1=='d')
	{
		t=t+1;
		cout<<"\n\n Correct answer....";

	}	else
		cout<<"\n\n Sorry Wrong answer....";
		getch();
		cout<<"\n\n\n";
		cout<<"7) Superconductivity is a material property associated with";
		cout<<"\n\n A. Cooling a substance without a phase change \n\n B.Frictionless liquid flow \n\n C.A loss of thermal resistance \n\n D. A loss of electrical resistance";
		cout<<"\n\n Enter Your Select answer : ";
		cin>>ch1;
	if(ch1=='d')
	{
		t=t+1;
		cout<<"\n\n Correct answer....";

	}	else
		cout<<"\n\n Sorry Wrong answer....";
		getch();
		cout<<"\n\n\n";
		cout<<"8) Which of the following is primarily composed of calcium carbonate?";
		cout<<"\n\n A.Fish Scales \n\n B.Shark teeths \n\n C.Oyester Shell \n\n D.Whale bones";
		cout<<"\n\n Enter Your Select answer : ";
		cin>>ch1;
	if(ch1=='c')
	{
		t=t+1;
		cout<<"\n\n Correct answer....";

	}	else
		cout<<"\n\n Sorry Wrong answer....";
		getch();
		cout<<"\n\n\n";
		cout<<"9) Yeast, used in making bread is a";
		cout<<"\n\n A.Fungus \n\n B.Plant \n\n C.Bacteria \n\n D.Seed";
		cout<<"\n\n Enter Your Select answer : ";
		cin>>ch1;
	if(ch1=='a')
	{
		t=t+1;
		cout<<"\n\n Correct answer....";

	}	else
		cout<<"\n\n Sorry Wrong answer....";
		getch();
		cout<<"\n\n\n";
		cout<<"10) A gas used as a disinfectant in drinking water is";
		cout<<"\n\n A.Chlorine \n\n B.Fluorine \n\n C.Hydrogen \n\n D.Boron";
		cout<<"\n\n Enter Your Select answer : ";
		cin>>ch1;
	if(ch1=='a')
	{
		t=t+1;
		
		cout<<"\n\n Correct answer....";

	}	else
		cout<<"\n\n Sorry Wrong answer....";
		getch();
		cout<<"\n\n\n";
		cout<<"11) There are rings around which of the following?";
		cout<<"\n\n A.Jupiter \n\n B.Mars \n\n C.Uranus \n\n D.Saturn";
		cout<<"\n\n Enter Your Select answer : ";
		cin>>ch1;
	if(ch1=='d')
	{
		t=t+1;
		cout<<"\n\n Correct answer....";

	}	else
		cout<<"\n\n Sorry Wrong answer....";
		getch();
		cout<<"\n\n\n";
		cout<<"12) The hardest substance available on earth is";
		cout<<"\n\n A.Platinum \n\n B.Diamond \n\n C.Asbestos \n\n D.Quartz";
		cout<<"\n\n Enter Your Select answer : ";
		cin>>ch1;
	if(ch1=='b')
	{
		t=t+1;
		cout<<"\n\n Correct answer....";

	}	else
		cout<<"\n\n Sorry Wrong answer....";
		getch();
		cout<<"\n\n\n";
		cout<<"13) The removal of top soil by water or wind is called ";
		cout<<"\n\n A.Soil wash  \n\n B.Soil erosion \n\n C.Soil creep \n\n D.Salinity";
		cout<<"\n\n Enter Your Select answer : ";
		cin>>ch1;
	if(ch1=='b')
	{
		t=t+1;
		cout<<"\n\n Correct answer....";

	}
	else
		cout<<"\n\n Sorry Wrong answer....";
		getch();
		cout<<"\n\n\n";
		cout<<"14) The Panda belongs to the same family as that of ";
		cout<<"\n\n A.Bear \n\n B.Cat \n\n C.Leopard \n\n D.Rabbit";
		cout<<"\n\n Enter Your Select answer : ";
		cin>>ch1;
	if(ch1=='a')
	{
		t=t+1;
		cout<<"\n\n Correct answer...";
	}
	else
		cout<<"\n\n Sorry Wrong answer....";
		getch();
		cout<<"\n\n\n";
		cout<<"15) The intensity of Earthquakes is measured on ";
		cout<<"\n\n A.Ritcher Scale \n\n B.Secant scale \n\n C.Mercalli scale \n\n D.Bernaulli Scale";
		cout<<"\n\n Enter Your Select answer : ";
		cin>>ch1;
	if(ch1=='a')
	{
		t=t+1;
		cout<<"\n\n Correct answer.....";
	}
	else
		cout<<"\n\n Sorry Wrong answer....";
		getch();
		cout<<"\n\n\n";
		cout<<"16) The gas predominantly responsible for global warning is";
		cout<<"\n\n A. Carbon dioxide \n\n B. Carbon monoxide \n\n C.Nitrous oxide \n\n D. Nitrogen peroxide";
		cout<<"\n\n Enter Your Select answer : ";
		cin>>ch1;

	if(ch1=='a')
	{
		t=t+1;
		cout<<"\n\n Correct answer...";
	}
	else
		cout<<"\n\n Sorry Wrong answer....";
		getch();
		cout<<"\n\n\n";
		cout<<"17) The blue colour of the clear sky is due to";
		cout<<"\n\n A.Diffraction of light \n\n B.Dispersion of light \n\n C.Reflection of light \n\n D.Refraction of light";
		cout<<"\n\n Enter Your Select answer : ";
		cin>>ch1;

	if(ch1=='b')
	{
		t=t+1;
		cout<<"\n\n Correct answer....";
	}
	else

		cout<<"\n\n Sorry Wrong answer....";
		cout<<"\n\n Enter Your Choice :--> ";
		cin>>n;

	case 2:

		if(t==17)
		cout<<"\n\n Congratulation......You are extremly intelligent.......Your score is 17";
		else if(t<=17)
	      cout<<"\n Total Score is : "<<t;
	      cout<<"\n\n Enter Your Choice :--> ";
	      cin>>n;

	case 3:
	int reply;
	    cout<<"\n\n Are Sure you want to exit quiz ? Y/N  :";
	    cin>>reply;
	    if(reply=='Y')
	    {
		break;
	    }
}
getch();
}
